export const CASTING_TIMES = {
  REACTION: "REACTION",
  BONUS_ACTION: "BONUS_ACTION",
  ACTION: "ACTION",
  ONE_MINUTE: "ONE_MINUTE",
  TEN_MINUTES: "TEN_MINUTES",
  ONE_HOUR: "ONE_HOUR",
  EIGHT_HOURS: "EIGHT_HOURS",
  TWELVE_HOURS: "TWELVE_HOURS",
  TWENTYFOUR_HOURS: "TWENTYFOUR_HOURS",
  SPECIAL: "SPECIAL",
};

export const LEVELS = {
  LEVEL_0: "LEVEL_0",
  LEVEL_1: "LEVEL_1",
  LEVEL_2: "LEVEL_2",
  LEVEL_3: "LEVEL_3",
  LEVEL_4: "LEVEL_4",
  LEVEL_5: "LEVEL_5",
  LEVEL_6: "LEVEL_6",
  LEVEL_7: "LEVEL_7",
  LEVEL_8: "LEVEL_8",
  LEVEL_9: "LEVEL_9",
};

export const SCHOOLS = {
  ABJURATION: "ABJURATION",
  CONJURATION: "CONJURATION",
  DIVINATION: "DIVINATION",
  ENCHANTMENT: "ENCHANTMENT",
  EVOCATION: "EVOCATION",
  ILLUSION: "ILLUSION",
  NECROMANCY: "NECROMANCY",
  TRANSMUTATION: "TRANSMUTATION",
};
