export const Schools = {
  ABJURATION: "ABJURATION",
  CONJURATION: "CONJURATION",
  DIVINATION: "DIVINATION",
  ENCHANTMENT: "ENCHANTMENT",
  EVOCATION: "EVOCATION",
  ILLUSION: "ILLUSION",
  NECROMANCY: "NECROMANCY",
  TRANSMUTATION: "TRANSMUTATION",
};
